name: smart_cache
description: "Smart Cache is a comprehensive caching solution that supports memory caching, compressed caching, and disk caching. It automatically manages active and inactive data to optimize performance."
version: 0.0.1
homepage:

environment:
  sdk: ^3.3.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  crypto: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
