name: smart_cache
description: "Smart Cache is a comprehensive caching solution that supports memory caching, compressed caching, and disk caching. It automatically manages active and inactive data to optimize performance."
version: 0.0.1
homepage:

environment:
  sdk: ^3.3.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: 3.0.3
  hive_ce_flutter: ^2.2.0
  hive_ce: ^2.10.1
  path_provider: ^2.1.5
  logger: ^2.0.2+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.15
